name = "New Altenbury Packwiz"
author = "RexcliffeTransit"
version = "25"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "795531e6da41d90f347c19d7554501246cf327666bd6d429176fda6758b10c14"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
