name = "New Altenbury Packwiz"
author = "RexcliffeTransit"
version = "25"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3b7856461081543d1b5afbb58f9c1183b8fe2454ee1340b2ad62b1c5c69710d8"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
