name = "New Altenbury Packwiz"
author = "RexcliffeTransit"
version = "25"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "94650c0083bc3b56d4b7fc4bdf6cdd6fd6acf6451a6b8dfdfcec75c788eadb4b"

[versions]
fabric = "0.18.2"
minecraft = "1.20.1"
